/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const IndustryType = IDL.Variant({
  'all' : IDL.Null,
  'forex' : IDL.Null,
  'crypto' : IDL.Null,
  'commodity' : IDL.Null,
});
export const ContactInquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'marketInterest' : IndustryType,
});

export const idlService = IDL.Service({
  'getAllContacts' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
  'submitContactInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IndustryType, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const IndustryType = IDL.Variant({
    'all' : IDL.Null,
    'forex' : IDL.Null,
    'crypto' : IDL.Null,
    'commodity' : IDL.Null,
  });
  const ContactInquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'marketInterest' : IndustryType,
  });
  
  return IDL.Service({
    'getAllContacts' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
    'submitContactInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IndustryType, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };